version: 2

updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    groups:
      web-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /netease-api
    schedule:
      interval: weekly
      day: monday
    groups:
      netease-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly
      day: monday
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /Android
    schedule:
      interval: weekly
      day: monday
    groups:
      android-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      workflow-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
