org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
kotlin.code.style=official

# Modified distributions should override this with their exact corresponding source.
# SOURCE_CODE_URL=https://github.com/your-account/your-fork
