# Love Journal - a private journal + blog + real-time interaction platform for couples.
# Copyright (C) 2026 Love Journal Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""add_media_policy_settings

Revision ID: c0efd7ec594c
Revises: 20260426_0422
Create Date: 2026-04-25 23:50:54.577117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c0efd7ec594c'
down_revision: Union[str, None] = '20260426_0422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('articles', 'is_co_created') # Skip drop to avoid complexity
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('site_settings', sa.Column('max_image_kb', sa.Integer(), nullable=False, server_default='1024'))
    op.add_column('site_settings', sa.Column('thumb_width', sa.Integer(), nullable=False, server_default='400'))
    op.add_column('site_settings', sa.Column('compress_quality', sa.Integer(), nullable=False, server_default='82'))
    op.add_column('site_settings', sa.Column('strip_exif', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('site_settings', sa.Column('allowed_image_types', sa.String(length=512), nullable=False, server_default='image/jpeg,image/png,image/webp,image/gif'))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_settings', 'allow_registration',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
    op.alter_column('site_settings', 'videos_path',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'uploads/videos'"),
               existing_nullable=False)
    op.alter_column('site_settings', 'timeline_path',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'uploads/timeline'"),
               existing_nullable=False)
    op.drop_column('site_settings', 'allowed_image_types')
    op.drop_column('site_settings', 'strip_exif')
    op.drop_column('site_settings', 'compress_quality')
    op.drop_column('site_settings', 'thumb_width')
    op.drop_column('site_settings', 'max_image_kb')
    op.alter_column('moments', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('moments', 'visibility',
               existing_type=sa.VARCHAR(length=13),
               server_default=sa.text("'public'"),
               existing_nullable=False)
    op.alter_column('messages', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('events', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('events', 'visibility',
               existing_type=sa.VARCHAR(length=13),
               server_default=sa.text("'public'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'result',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'success'"),
               existing_nullable=False)
    op.add_column('articles', sa.Column('is_co_created', sa.BOOLEAN(), nullable=False))
    op.alter_column('articles', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('albums', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    # ### end Alembic commands ###
